# Generated by Django 4.2.24 on 2025-09-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('media', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('environment', 'Environment'), ('innovation', 'Innovation'), ('equality', 'Equality')], default='health', max_length=50, verbose_name='SDG')),
                ('region', models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('kashkadarya', 'Kashkadarya'), ('samarkand', 'Samarkand'), ('sirdarya', 'Sirdarya'), ('surkhandarya', 'Surkhandarya'), ('tashkent', 'Tashkent'), ('karakalpakstan', 'Karakalpakstan'), ('khorezm', 'Khorezm')], default='tashkent', max_length=50, verbose_name='Region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='projects.project')),
            ],
        ),
    ]
