# Generated by Django 4.2.24 on 2025-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
