# Generated by Django 5.1.4 on 2025-09-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='media',
            new_name='image',
        ),
    ]
